name: build-resume

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий вместе со всеми подмодулями
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2) Собираем PDF в контейнере
      - name: Build PDF in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work \
            texlive/texlive:latest \
            latexmk -xelatex -interaction=nonstopmode resume.tex

      # 3) Отправляем артефакт
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
